import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from "next/font/google";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600", "700"] });

export const metadata: Metadata = {
  title: "Passwords",
  description: "Generated by Fvlsoft",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavBar />
        <div className="max-w-4xl mx-auto p-5">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
